# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Víctor S. Carmena
description: Padre. Ingeniero de software senior. Profesor. Co-organizador de Techne Forum. Mezcla de manchego, madrileño y catalán
author: Víctor S. Carmena
email: hola@vscarmena.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://vscarmena.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: vscarmena
github_username:  vscarmena
linkedin_username:  vscarmena

google_analytics: UA-114685196-1

excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

font-awesome:
  assets: true
unpublished: true
